version: "3.9"

services:

  client:
    image: ${IMAGE_NAME}
    restart: always
    environment:
      DATABASE_URL: ${DATABASE_URL}
      G_PORT: 3002
      PORT: 3000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.client.rule=Host(`rt-client.rt-provider.ru`)"
      - "traefik.http.routers.client.tls=true"
      - "traefik.http.routers.client.tls.certresolver=le"

networks:
  default:
    name: rostelecom-network
    external: true